version: '3.1'
services:
  mibiao:
    build:
      context: .
      dockerfile: Dockerfile
    image: mibiao
    container_name: 'mibiao'
    ports:
      - ${WEBSERVER_PORT:-8080}:8080
    working_dir: /mibiao_data
    volumes:
      - ./mibiao_data:/mibiao_data
    restart: always
    command: [
      'gunicorn',
      '--log-level=INFO',
      '--capture-output',
      '--access-logfile','-',
      '--error-logfile', '-',
      '-b', '0.0.0.0:8080',
      '-k', 'gevent',
      '-w', '1',
      '-t', '10',
      'mibiao.app:app'
    ]
    logging:
      driver: 'json-file'
      options:
        max-size: '10M'
        max-file: '10'