version: '3.1'
services:
  mibiao:
    build:
      context: .
      dockerfile: Dockerfile
    image: mibiao
    container_name: 'mibiao'
    ports:
      - ${WEBSERVER_PORT:-8080}:8080
    working_dir: /mibiao_data
    volumes:
      - ./mibiao_data:/mibiao_data
    restart: always
    command: [
      'gunicorn',
      '-c', '/opt/mibiao/mibiao/gunicorn.conf.py'
      '-b', '0.0.0.0:15000', # ipv4 + 端口
      '-b' ,'[::]:15000', # ipv6 + 端口
      'mibiao.app:app'
    ]
    logging:
      driver: 'json-file'
      options:
        max-size: '10M'
        max-file: '10'