version: '3.1'
services:
  mibiao:
    build:
      context: .
      dockerfile: Dockerfile
    image: mibiao
    container_name: 'mibiao'
    ports:
      - ${WEBSERVER_PORT:-8080}:8080
    working_dir: /mibiao_data
    volumes:
      - ./mibiao_data:/mibiao_data
    restart: always
    command: [ 'mibiao', 'run', '--host=0.0.0.0', '--port=8080' ]
    logging:
      driver: 'json-file'
      options:
        max-size: '10M'
        max-file: '10'


# docker-compose pull

# docker-compose build

# docker-compose down && docker-compose up -d
