[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'mibiao'
version = '0.0.1'
requires-python = '>=3.11,<3.12'
dependencies = [
    'click==8.1.7',
    'Werkzeug==3.0.3',
    'Flask==3.0.3',
    'email_validator==2.1.1',
    'WTForms==3.1.2',
    'Flask-WTF==1.2.1',
    'SQLAlchemy==2.0.30',
    'Flask-SQLAlchemy==3.1.1',
    'Flask-Login==0.6.3',
    'gevent==24.2.1',
    'gunicorn==22.0.0',
    'pydantic==2.7.4',
    'pydantic-settings==2.2.1',
    'pendulum==3.0.0',
    'filelock==3.15.1',
]
[project.scripts]
mibiao = 'mibiao.cli:cli'

[tool.setuptools.packages.find] # https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
where = ['src']
include = ['*']

[tool.setuptools.package-data]
'*' = ['*.*']
